apiVersion: v1
kind: Service
metadata:
  labels:
    app: jupyter-hub-deployment
  name: jupyter-hub-service
  namespace: default
spec:
  ports:
  - name: 8000-to-8000-tcp
    port: 8000
    protocol: TCP
    targetPort: 8000
  - name: 8081-to-8081-tcp
    port: 8081
    protocol: TCP
    targetPort: 8081
  selector:
    app: jupyter-hub-deployment
  type: ClusterIP