FROM jupyter/datascience-notebook

# install pinned jupyterhub and ensure notebook is installed
RUN python3 -m pip install jupyter && \
    python3 -m pip install jupyterhub && \
    python3 -m pip install notebook